- name: variables to print
  hosts: web
  vars:
    COURSE: devops with AWS
    DURATION: 120 HOURS
    TRAINER: Sivakumar reddy
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, i am learning the {{COURSE}},Duration is{{DURATION}},Trainer is{{TRAINER}}"

  - name: print the information
    vars:
    COURSE: Ansible
    ansible.builtin.debug:
      msg: "Hi, i am learning the {{COURSE}},Duration is{{DURATION}},Trainer is{{TRAINER}}"

  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, i am learning the {{COURSE}},Duration is{{DURATION}},Trainer is{{TRAINER}}"

  