- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enter the Course name
  - name: TRAINER
    prompt: please enter the trainer name
  tasks:
  - name: print the variables from prompt
    ansible.builtin.debug:
      msg: "Hi, i am learning the {{COURSE}},Duration is{{DURATION}},Trainer is{{TRAINER}}"s