- name : create user
  hosts: web
  become: yes
  tasks:
   - name: check the user exist or not
     ansible.builtin.command: id expense
     register: USER

   - name: print user information
      ansible.builtin.debug:
        msg: "user info: {{USER}}"
