- name: filters demo
  hosts: web
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "hello{{course|default ('Ansible')}}"

  - name: convert to upper case
    vars:
      greeting: "hello ramesh"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

  - name: convert to lower case
    vars:
      greeting: "hello ramesh"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"
    
  - name: print unique number
    vars:
      numbers: [1,2,22,3,4,4,7,8,1,1]
    ansible.builtin.debug:
      msg: '{{ numbers | unique }}'
      
